name: beyond2lte

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 100

      - name: Checkout gcc toolchain
        uses: actions/checkout@v3
        with:
          repository: mvaisakh/gcc-arm64
          ref: 05cb20a52f12389c3f2340b5103485108feae302
          path: toolchain

      - name: Fetch KernelSU
        run: |
          git submodule update --init --recursive

      - name: Android kernel build
        run: |
          sudo apt install libdebuginfod-dev
          export PATH="$(pwd)/toolchain/bin:${PATH}"
          bash build.sh none beyond2lte
          git log --no-decorate --oneline -n 100 > out/ak3/ChangeLog.txt

      - name: Upload final output
        uses: actions/upload-artifact@v3
        with:
          name: release-ksu
          path: |
            out/ak3/ChangeLog.txt
            out/ak3/*.zip