name: beyond2lte

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4.1.1
        with:
          submodules: 'true'
          fetch-depth: 100

      - name: Ccache for gh actions
        uses: hendrikmuhs/ccache-action@v1.2.10

      - name: Checkout gcc toolchain
        uses: actions/checkout@v4.1.1
        with:
          repository: mvaisakh/gcc-arm64
          ref: 05cb20a52f12389c3f2340b5103485108feae302
          path: toolchain

      - name: Fetch KernelSU
        run: |
          git submodule update --init --recursive

      - name: Android kernel build
        run: |
          sudo apt install libdebuginfod-dev
          export PATH="$(pwd)/toolchain/bin:${PATH}"
          bash build.sh none beyond2lte
          git log --no-decorate --oneline -n 100 > out/ak3/ChangeLog.txt
          latest_version_of_kernel_su=$(curl -s https://api.github.com/repos/tiann/KernelSU/releases/latest | jq -r '.tag_name')
          timestamp=$(TZ=UTC-8 date +%Y%m%d%H%M)
          final_tag="${latest_version_of_kernel_su}.${timestamp}"  # Consistent naming
          echo "FINAL_TAG=$final_tag" >> $GITHUB_ENV  # Set only the necessary variable
          

      - name: Upload final output
        uses: actions/upload-artifact@v4.0.0
        with:
          name: release-ksu
          path: |
            out/ak3/ChangeLog.txt
            out/ak3/*.zip

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ env.FINAL_TAG }}
          automatic_release_tag: ${{ env.FINAL_TAG }}
          prerelease: false
          files: |
            out/ak3Image
            out/ak3/*.zip*.zip