name: "tagged-release"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4.1.1
        with:
          submodules: 'true'
          fetch-depth: 100

      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ env.FINAL_TAG }}
          automatic_release_tag: ${{ env.FINAL_TAG }}
          prerelease: false
          run: |
            ls
          files: |
            ${pwd}/build.sh
            ${pwd}/out/ak3/*.zip
