name: "tagged-release"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4.1.1
        with:
          submodules: 'true'
          fetch-depth: 100

      - name: "Build & test"
        run: |
          latest_version_of_kernel_su=$(curl -s https://api.github.com/repos/tiann/KernelSU/releases/latest | jq -r '.tag_name')
          timestamp=$(TZ=UTC-8 date +%Y%m%d%H%M)
          final_tag="${latest_version_of_kernel_su}.${timestamp}"  # Consistent naming
          echo "FINAL_TAG=$final_tag" >> $GITHUB_ENV  # Set only the necessary variable
          echo "done!"
          ls

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ env.FINAL_TAG }}
          automatic_release_tag: ${{ env.FINAL_TAG }}
          prerelease: false
          run: |
            ls
          files: |
            build.sh
            exynos9820.cfg
            build.config.aarch64
